# docker-compose.ci.yml
version: '3.9'

services:
  postgres:
    ports:
      - "15432:5432"  # Different external port
  
  redis:
    ports:
      - "16379:6379"  # Different external port
  
  agtsdbx:
    environment:
      # Override to use GitHub Actions services if needed
      - DATABASE_URL=postgresql://agtsdbx:agtsdbx_dev_password@postgres:5432/agtsdbx
      - REDIS_HOST=redis
  
  frontend:
    environment:
      - AGTSDBX_BASE_URL=http://agtsdbx:8000
