name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  quick-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build test images
        run: |
          docker compose build --parallel
          
      - name: Run quick tests
        run: |
          docker compose up -d
          sleep 15
          curl -f http://localhost:8000/health || echo "Backend not ready"
          curl -f http://localhost:8080/api/health || echo "Frontend not ready"
          docker compose down
          
      - name: Comment PR
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Quick tests completed. Check the Actions tab for details.'
            })
